# Use root/example as user/password credentials

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: michaelfilippo
      MONGO_INITDB_ROOT_PASSWORD: GYLxX0xDrw4ON7DM
